from analysis_engine import analyze_input


def test_analyze_input_rule_mode_outputs_api_metadata():
    code = (
        "def search_user(name):\n"
        "    sql = \"SELECT * FROM users WHERE name='\" + name + \"'\"\n"
        "    return conn.execute(sql)\n"
    )
    result = analyze_input(input_type="code", ai_mode="rule", code=code)

    assert result["languages"] == ["zh-CN", "en-US"]
    assert result["api_called"] is False
    assert result["api_models"] == []
    assert result["vulnerabilities"]
    finding = result["vulnerabilities"][0]
    assert finding["type"] == "SQL Injection"
    assert finding["api_called"] is False
    assert finding["model_used"] is None
    assert finding["bilingual"]["type"]["en"] == "SQL Injection"
    assert finding["bilingual"]["type"]["zh"] == "SQL 注入"
    assert finding["bilingual"]["patch_reason"]["en"]
    assert finding["bilingual"]["patch_reason"]["zh"] == finding["patch_reason"]
    assert result["display"]["zh"]["vulnerabilities"]
    assert result["display"]["zh"]["vulnerabilities"][0]["漏洞类型"] == "SQL 注入"


def test_analyze_input_cloud_mode_outputs_model_used(monkeypatch):
    code = (
        "def search_user(name):\n"
        "    sql = \"SELECT * FROM users WHERE name='\" + name + \"'\"\n"
        "    return conn.execute(sql)\n"
    )

    def fake_generate_ai_text(ai_mode: str, prompt: str, model_name: str | None = None):
        assert ai_mode == "cloud"
        return "# fake patch", model_name or "gpt-4.1"

    monkeypatch.setattr("analysis_engine.generate_ai_text", fake_generate_ai_text)
    result = analyze_input(
        input_type="code",
        ai_mode="cloud",
        model_name="gpt-4.1",
        code=code,
    )

    assert result["api_called"] is True
    assert result["api_models"] == ["gpt-4.1"]
    assert result["vulnerabilities"]
    assert result["vulnerabilities"][0]["api_called"] is True
    assert result["vulnerabilities"][0]["model_used"] == "gpt-4.1"
    assert result["vulnerabilities"][0]["bilingual"]["patch_mode"] == {
        "en": "cloud",
        "zh": "云端 AI",
    }
    assert result["vulnerabilities"][0]["bilingual"]["patch_reason"] == {
        "en": "Generated by cloud AI.",
        "zh": "云端 AI 生成",
    }


def test_analyze_input_no_vulnerability_outputs_chinese_message():
    code = "def hello(name):\n    return f'hello {name}'\n"
    result = analyze_input(input_type="code", ai_mode="rule", code=code)

    assert result["count"] == 0
    assert result["vulnerabilities"] == []
    assert result["skipped_files"] == []
    assert result["display"]["zh"]["message"] == "未检测到漏洞。"


def test_analyze_input_invalid_python_outputs_skip_details():
    result = analyze_input(input_type="code", ai_mode="rule", code="def broken(:\n")

    assert result["count"] == 0
    assert result["skipped_files"] == ["input.py"]
    assert result["skipped_details"]
    assert result["skipped_details"][0]["file"] == "input.py"
    assert "Code parsing failed" in result["skipped_details"][0]["reason_en"]
    assert "代码解析失败" in result["skipped_details"][0]["reason_zh"]
    assert result["display"]["zh"]["skipped_files"]
    assert "代码解析失败" in result["display"]["zh"]["skipped_files"][0]["原因"]


def test_analyze_input_cloud_no_vulnerability_explains_no_api_call():
    code = "def hello(name):\n    return f'hello {name}'\n"
    result = analyze_input(
        input_type="code",
        ai_mode="cloud",
        model_name="gpt-4.1",
        code=code,
    )

    assert result["count"] == 0
    assert result["api_called"] is False
    assert result["api_models"] == []
    assert result["display"]["zh"]["message"] == "未发现漏洞，因此未调用模型生成补丁。"
