"""
Core data models for the VulnPatch audit platform.

This module defines the unified data models used across the audit pipeline:
- CodeUnit: Input code representation
- RawFinding: Detector output
- AgentHypothesis: LLM agent analysis results
- EvidenceBundle: Consolidated evidence for findings
- AuditResult: Final audit output
"""

from typing import Any, Optional
from pydantic import BaseModel, Field
from datetime import datetime
import uuid


def generate_id() -> str:
    """Generate a unique identifier."""
    return str(uuid.uuid4())[:8]


class CodeUnit(BaseModel):
    """
    Represents a unit of code input for analysis.
    
    This can be a file, a code snippet, or any other code unit
    that needs to be analyzed for vulnerabilities.
    """
    id: str = Field(default_factory=generate_id)
    path: str = Field(..., description="File path or identifier for the code unit")
    language: str = Field(..., description="Programming language (e.g., python, javascript)")
    content: str = Field(..., description="Actual code content")
    start_line: int = Field(default=1, description="Starting line number in the original file")
    end_line: Optional[int] = Field(default=None, description="Ending line number in the original file")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

    class Config:
        frozen = False


class RawFinding(BaseModel):
    """
    Represents a raw finding from an analyzer.
    
    This is the output format for all static analysis engines
    (pattern matching, AST analysis, taint analysis, etc.).
    """
    id: str = Field(default_factory=generate_id)
    rule_id: str = Field(..., description="Identifier of the rule that triggered this finding")
    type: str = Field(..., description="Vulnerability type (e.g., SQL Injection)")
    cwe: Optional[str] = Field(default=None, description="CWE identifier (e.g., CWE-89)")
    severity: str = Field(default="UNKNOWN", description="Severity level: ERROR, WARN, INFO, etc.")
    confidence: str = Field(default="low", description="Confidence level: high, medium, low")
    file_path: str = Field(..., description="Path to the file containing the vulnerability")
    start_line: int = Field(..., description="Starting line number of the vulnerable code")
    end_line: Optional[int] = Field(default=None, description="Ending line number")
    message: str = Field(..., description="Human-readable description of the finding")
    engine: str = Field(..., description="Name of the analyzer that produced this finding")
    evidence: dict[str, Any] = Field(default_factory=dict, description="Additional evidence data")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

    class Config:
        frozen = False


class AgentHypothesis(BaseModel):
    """
    Represents a hypothesis generated by an LLM agent.
    
    Agents analyze findings and generate hypotheses about
    potential vulnerabilities without storing full chain-of-thought.
    """
    id: str = Field(default_factory=generate_id)
    agent_name: str = Field(..., description="Name of the agent that generated this hypothesis")
    finding_id: Optional[str] = Field(default=None, description="Reference to the related finding")
    hypothesis: str = Field(..., description="The hypothesis text")
    vulnerability_type: Optional[str] = Field(default=None, description="Classified vulnerability type")
    reasoning_summary: str = Field(..., description="Concise reasoning summary (not full CoT)")
    confidence: str = Field(default="low", description="Confidence level: high, medium, low")
    supporting_evidence_ids: list[str] = Field(default_factory=list, description="IDs of supporting evidence")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

    class Config:
        frozen = False


class AgentLog(BaseModel):
    """
    Represents a log entry from an agent's execution.
    
    Tracks what agents do during the audit process for
    debugging and transparency purposes.
    """
    id: str = Field(default_factory=generate_id)
    agent_name: str = Field(..., description="Name of the agent")
    stage: str = Field(..., description="Execution stage (e.g., recon, analysis, judge)")
    message: str = Field(..., description="Log message")
    input_refs: list[str] = Field(default_factory=list, description="References to input objects")
    output_refs: list[str] = Field(default_factory=list, description="References to output objects")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Log timestamp")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

    class Config:
        frozen = False


class JudgeDecision(BaseModel):
    """
    Represents a decision made by the Judge Agent.
    
    The Judge Agent evaluates findings and hypotheses to make
    a final determination about the validity of a vulnerability.
    """
    id: str = Field(default_factory=generate_id)
    finding_id: str = Field(..., description="Reference to the finding being judged")
    verdict: str = Field(..., description="Verdict: confirmed, suspicious, or rejected")
    confidence: str = Field(..., description="Confidence in the verdict: high, medium, low")
    risk_score: float = Field(..., description="Calculated risk score (0-100)")
    reason: str = Field(..., description="Explanation for the decision")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

    class Config:
        frozen = False


class EvidenceBundle(BaseModel):
    """
    Represents a complete evidence package for a finding.
    
    Consolidates all information about a potential vulnerability
    including code snippets, call chains, agent analysis, and judge decision.
    """
    id: str = Field(default_factory=generate_id)
    finding: RawFinding = Field(..., description="The original finding")
    code_unit: Optional[CodeUnit] = Field(default=None, description="The code unit containing the vulnerability")
    snippets: list[dict[str, Any]] = Field(default_factory=list, description="Code snippets as evidence")
    call_chain: list[dict[str, Any]] = Field(default_factory=list, description="Call chain information")
    agent_hypotheses: list[AgentHypothesis] = Field(default_factory=list, description="Agent hypotheses")
    agent_logs: list[AgentLog] = Field(default_factory=list, description="Agent execution logs")
    judge_decision: Optional[JudgeDecision] = Field(default=None, description="Judge agent decision")
    cwe_info: dict[str, Any] = Field(default_factory=dict, description="CWE classification information")
    score_breakdown: dict[str, Any] = Field(default_factory=dict, description="Risk score breakdown")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

    class Config:
        frozen = False


class AuditSummary(BaseModel):
    """
    Summary statistics for an audit run.
    """
    total_code_units: int = Field(default=0, description="Total number of code units analyzed")
    total_findings: int = Field(default=0, description="Total number of findings")
    total_evidence_bundles: int = Field(default=0, description="Total number of evidence bundles")
    risk_score: float = Field(default=0.0, description="Overall risk score (0-100)")
    languages: list[str] = Field(default_factory=list, description="Languages analyzed")
    scanned_files: list[str] = Field(default_factory=list, description="List of scanned file paths")

    class Config:
        frozen = False


class AuditResult(BaseModel):
    """
    Complete result of an audit run.
    
    This is the main output format for the audit platform,
    consumed by API, UI, and report layers.
    """
    summary: AuditSummary = Field(..., description="Audit summary statistics")
    findings: list[RawFinding] = Field(default_factory=list, description="All findings")
    evidence: list[EvidenceBundle] = Field(default_factory=list, description="Evidence bundles for findings")
    agent_logs: list[AgentLog] = Field(default_factory=list, description="Agent execution logs")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

    class Config:
        frozen = False

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return self.model_dump(mode="json")
